[package]
name = "macro_plugin"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
proc-macro2 = "1"
syn = { version = "2.0.89", features = ["full"] }
quote = "1"

[lib]
proc-macro = true

