[package]
name = "plugin_screen_kit"
version = { workspace = true }
edition = { workspace = true }




[lib]
crate-type = ["cdylib"]

[dependencies]
macro_plugin = { workspace = true }
plugin = { workspace = true }

